name: Build and Test

on:
  push:
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - run: npm install

      - run: npm run build

      - run: npm test
        env:
          CI: true
